<div class="page-heading">

</div>
            <h1><?php echo 'Data' ?></h1>
<table>
    <thead>
        <tr>
            <th><?php echo __('Name')?></th>
            <th><?php echo __('Email')?></th>
            <th><?php echo __('Division')?></th>
            <th><?php echo __('Status')?></th>
            <th><?php echo __('Order_Counter')?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->getTraineeCollection() as $trainees) : ?>
        <tr>
            <td><?php echo $trainees->getName() ?></td>
            <td><?php echo $trainees->getEmail() ?></td>
            <td><?php echo $trainees->getDivision() ?></td>
            <td><?php echo $trainees->getStatus() ?></td>
            <td><?php echo $trainees->getOrderCounter() ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<form class="form form-login"
        action="<?php /* @escapeNotVerified */ echo $block->getUrl('input/input/index'); ?>">
        <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('Back') ?></span></button></div>
</form>