<style>
table th,table td { border: 1px solid #DDD; }

table th { background: #26a8e0; color: #FFF; }

.text-center { text-align: center; }
</style>

<div class="page-heading">
	<h1>Data</h1>
</div>
<table>
    <thead>
        <tr>
    	    <th class="text-center">No</th>
                <th><?php echo __('Name')?></th>
    	    <th><?php echo __('Email')?></th>
                <th><?php echo __('Division')?></th>
    	    <th><?php echo __('Status')?></th>
    	    <th></th>
        </tr>
    </thead>
    <tbody>
	<?php $no = 1 ?>
        <?php foreach ($this->getEmployeeCollection() as $employees) : ?>
        <tr>
	    <td class="text-center"><?php echo $no ?></td>
	    <td><?php echo $employees->getNama() ?></td>
            <td><?php echo $employees->getEmail() ?></td>
	    <td><?php echo $employees->getDivision() ?></td>
        <td>
            <?php if($employees->getStatus() == 1): 
            echo '<span style="color: green; ">Employee</span>'; 
            else:
            echo '<span style="color: red; ">Unemployee</span>';
            endif;
            ?>
        </td>
        <td><a href="http://facebook.com/<?php echo $employees->getId_employee ?> ">Hapus</a></td>
	    <?php $no++; ?>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
