<div >
   <div class="block-content" aria-labelledby="block-customer-login-heading">
       <form class="form "
             action="<?php /* @escapeNotVerified */ $this->getUrl('Training/index/create'); ?>"
             method="post"
             id="quiz-form"
             >
               <label for="fname">Nama</label>
               <input type="text" id="fname" name="name" placeholder="Your name..">

               <label for="lname">Email</label>
               <input type="text" id="lname" name="email" placeholder="Your email..">

               <label for="lname">Divisi</label>
               <input type="text" id="lname" name="divisi" placeholder="Your division..">

               <input type="submit" value="Submit">
       </form>
   </div>
</div>